In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
singles = pd.read_hdf("singles_230801.h5")
singles.head()

,NAME,OLD_SPT,WAVE,FLUX,UNCERTAINTY,J_SNR,MKO_J,MKO_H,MKO_K,2MASS_J,2MASS_H,2MASS_KS,SPT
0,2MASS J11304030+1206306,M6.0,"[0.90129393, 0.9047135, 0.9081512, 0.9116069, ...","[1.9660627713093847e-10, 2.1131039893243844e-1...","[5.982245325049133e-12, 5.755711185801827e-12,...",94.018303,10.28,9.756188,9.363207,10.318813,9.706062,9.380460,M6.0
1,GAT 1370,M6.0,"[0.90129393, 0.9047135, 0.9081512, 0.9116069, ...","[1.9950771920752281e-10, 2.079591490944689e-10...","[7.703832533018333e-13, 1.0951267822400711e-12...",386.537811,10.28,9.843838,9.431730,10.327964,9.784580,9.454359,M7.0
2,2MASS J04314644+2506236,M6.0,"[0.90129393, 0.9047135, 0.9081512, 0.9116069, ...","[1.9762911463072993e-10, 2.0580528498234088e-1...","[2.2989224859548107e-12, 2.3022679333025286e-1...",204.598099,10.28,9.758637,9.359883,10.321691,9.701496,9.382371,M6.0
3,2MASS J01405263+0453302,M6.0,"[0.90129393, 0.9047135, 0.9081512, 0.9116069, ...","[2.2878515319813078e-10, 2.370316420618723e-10...","[6.1214909391048044e-12, 6.136043777530829e-12...",91.589699,10.28,9.767727,9.404947,10.314496,9.720459,9.430291,M6.0
4,V* FW Tau,M6.0,"[0.90129393, 0.9047135, 0.9081512, 0.9116069, ...","[2.0618668468240422e-10, 2.142866617637176e-10...","[1.0832266058640476e-12, 1.0976881329239517e-1...",414.787994,10.28,9.745862,9.373990,10.321529,9.687609,9.395473,M6.0

In [3]:
singles.dropna().shape #no missing values

(1049, 13)

In [4]:
# standards = pd.read_hdf("standards_230801.h5").reset_index(drop = True)
# standards.head()

In [23]:
#FILTER DATA BY SNR THRESHOLD
singles = singles[singles["J_SNR"] > 50].reset_index()

In [24]:
singles["SPT"].str[0].value_counts()

SPT
L    393
M    316
T     71
Name: count, dtype: int64

In [25]:
singles["WAVE"]

0      [0.90129393, 0.9047135, 0.9081512, 0.9116069, ...
1      [0.90129393, 0.9047135, 0.9081512, 0.9116069, ...
2      [0.90129393, 0.9047135, 0.9081512, 0.9116069, ...
3      [0.90129393, 0.9047135, 0.9081512, 0.9116069, ...
4      [0.90129393, 0.9047135, 0.9081512, 0.9116069, ...
                             ...
775    [0.90129393, 0.9047135, 0.9081512, 0.9116069, ...
776    [0.90129393, 0.9047135, 0.9081512, 0.9116069, ...
777    [0.90129393, 0.9047135, 0.9081512, 0.9116069, ...
778    [0.90129393, 0.9047135, 0.9081512, 0.9116069, ...
779    [0.90129393, 0.9047135, 0.9081512, 0.9116069, ...
Name: WAVE, Length: 780, dtype: object

In [26]:
all([1.2522339 in singles["WAVE"][i] for i in range(len(singles))])

True

In [28]:
#FIND WHICH FEATURE VALUE TO SET TO 1
np.where(singles["WAVE"][0] == 1.2522339)

(array([88], dtype=int64),)

In [32]:
flux_vals = pd.DataFrame(singles['FLUX'].to_list(), columns=[f'FLUX_{i}' for i in range(409)])
flux_vals

,FLUX_0,FLUX_1,FLUX_2,FLUX_3,FLUX_4,FLUX_5,FLUX_6,FLUX_7,FLUX_8,FLUX_9,...,FLUX_399,FLUX_400,FLUX_401,FLUX_402,FLUX_403,FLUX_404,FLUX_405,FLUX_406,FLUX_407,FLUX_408
0,1.966063e-10,2.113104e-10,2.215433e-10,2.269169e-10,2.322451e-10,2.340153e-10,2.264532e-10,2.183886e-10,2.115621e-10,2.069354e-10,...,5.567336e-11,5.740236e-11,5.390640e-11,5.251170e-11,5.513286e-11,5.493691e-11,5.639457e-11,5.432719e-11,5.391179e-11,5.327284e-11
1,1.995077e-10,2.079591e-10,2.186989e-10,2.314572e-10,2.396579e-10,2.406922e-10,2.316760e-10,2.244714e-10,2.172734e-10,2.145852e-10,...,5.591276e-11,5.510603e-11,5.385560e-11,5.270259e-11,5.162297e-11,5.110227e-11,5.155890e-11,5.132251e-11,5.090229e-11,4.999533e-11
2,1.976291e-10,2.058053e-10,2.110781e-10,2.208615e-10,2.230184e-10,2.221202e-10,2.202383e-10,2.149109e-10,2.121254e-10,2.125676e-10,...,6.030007e-11,5.930177e-11,5.825345e-11,5.708731e-11,5.563603e-11,5.537576e-11,5.549699e-11,5.508036e-11,5.505448e-11,5.516143e-11
3,2.287852e-10,2.370316e-10,2.375884e-10,2.509034e-10,2.579899e-10,2.514759e-10,2.553226e-10,2.390649e-10,2.428736e-10,2.483194e-10,...,5.932869e-11,5.623817e-11,5.618077e-11,5.312362e-11,5.069763e-11,5.341758e-11,5.426651e-11,5.488549e-11,5.353450e-11,5.553981e-11
4,2.061867e-10,2.142867e-10,2.222571e-10,2.337803e-10,2.400063e-10,2.379782e-10,2.291644e-10,2.187137e-10,2.130538e-10,2.069773e-10,...,5.953048e-11,5.892096e-11,5.671666e-11,5.483825e-11,5.366042e-11,5.395389e-11,5.447250e-11,5.488026e-11,5.409111e-11,5.382424e-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,2.764029e-13,3.307356e-13,3.576393e-13,3.690560e-13,3.887567e-13,3.855736e-13,3.827585e-13,3.014941e-13,2.918919e-13,3.500694e-13,...,2.972225e-14,2.829763e-14,2.130946e-14,2.605514e-14,3.349491e-14,4.642907e-14,2.913112e-14,2.256142e-14,5.799927e-14,5.906679e-14
776,7.445851e-14,1.715176e-13,1.100256e-13,1.563118e-13,2.222007e-13,1.855662e-13,2.237169e-13,2.104923e-13,1.300285e-13,1.594532e-13,...,1.693569e-14,1.875006e-14,5.982762e-14,4.193547e-14,2.472138e-14,4.787327e-15,-8.194454e-15,9.419336e-15,2.554327e-14,5.296454e-14
777,1.471659e-13,1.548241e-13,1.961845e-13,2.026734e-13,1.934860e-13,2.164524e-13,2.391653e-13,2.346124e-13,1.033603e-13,1.210646e-13,...,3.514339e-14,9.510527e-15,-1.465380e-14,4.932109e-15,2.413519e-14,3.030121e-14,1.857368e-14,5.847467e-16,1.804605e-14,1.752175e-14
778,1.522874e-13,1.843104e-13,2.281716e-13,2.356922e-13,2.393299e-13,2.438318e-13,2.408585e-13,2.282473e-13,2.170275e-13,2.037369e-13,...,6.763231e-15,1.522751e-15,1.713702e-14,2.222830e-14,2.963746e-14,2.089397e-14,1.605245e-14,2.200459e-14,3.167999e-14,2.405143e-14
779,5.706412e-14,6.531267e-14,6.459818e-14,6.837790e-14,7.865742e-14,7.978109e-14,7.727121e-14,7.826316e-14,5.090229e-14,5.881023e-14,...,1.646116e-15,-1.050513e-14,2.116823e-16,-4.273987e-15,-4.245786e-15,1.814186e-15,6.938255e-15,4.947017e-15,6.111873e-15,-6.411571e-16

In [44]:
# PER-ROW NORMALIZATION TO 1.25 micrometer FLUX VALUE (OR SHOULD WE DO NORMALIZATION TO AVERAGE OF 1.25 micrometer FLUX VALUE?)
flux_vals_normalized = flux_vals.apply(lambda row: row / row.iloc[88], axis=1)

In [56]:
# PER-ROW 0-1 NORMALIZATION (MAX-MIN NORMALIZATION USING PER-ROW MAX FLUX AND MIN FLUX)
flux_vals_row_max_min_norm = flux_vals.apply(lambda row: (row - row.min()) / (row.max() - row.min()), axis=1)
flux_vals_row_max_min_norm.describe()

,FLUX_0,FLUX_1,FLUX_2,FLUX_3,FLUX_4,FLUX_5,FLUX_6,FLUX_7,FLUX_8,FLUX_9,...,FLUX_399,FLUX_400,FLUX_401,FLUX_402,FLUX_403,FLUX_404,FLUX_405,FLUX_406,FLUX_407,FLUX_408
count,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,...,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000
mean,0.213644,0.240102,0.275038,0.315421,0.351763,0.367136,0.365637,0.356843,0.345696,0.347106,...,0.078018,0.075708,0.070296,0.063299,0.057107,0.054965,0.057272,0.059250,0.056944,0.054005
std,0.216748,0.224432,0.231240,0.240390,0.246648,0.244255,0.236014,0.225470,0.218509,0.212108,...,0.100288,0.100870,0.100119,0.099745,0.100210,0.100396,0.100753,0.100797,0.100486,0.100965
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.034232,0.046650,0.029584,0.000000,0.023763,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.018439,0.042046,0.071602,0.097882,0.123216,0.139409,0.146427,0.152360,0.151286,0.159417,...,0.027355,0.024466,0.019087,0.012248,0.005442,0.002825,0.004885,0.006488,0.004367,0.000057
50%,0.141479,0.168630,0.204980,0.254249,0.290453,0.314326,0.312312,0.304217,0.294871,0.294926,...,0.035426,0.033593,0.027188,0.019370,0.012835,0.009010,0.012627,0.015222,0.012376,0.009213
75%,0.364315,0.402279,0.445608,0.498987,0.549681,0.570288,0.556608,0.540670,0.519836,0.508143,...,0.070792,0.069001,0.057749,0.053506,0.048015,0.047322,0.048232,0.053156,0.047943,0.044399
max,0.826717,0.864999,0.867583,0.929394,0.962291,0.941540,0.949909,0.909442,0.911911,0.917399,...,0.656631,0.658513,0.648523,0.644155,0.634584,0.628031,0.648366,0.646237,0.649168,0.659353

In [57]:
#OVERALL 0-1 NORMALIZATION (USING MAX OVERALL FLUX AND MIN OVERALL FLUX)
max_flux = flux_vals.max().max()
min_flux = flux_vals.min().min()
flux_vals_overall_max_min_norm = flux_vals.apply(lambda row: (row - min_flux) / (max_flux - min_flux), axis=1)
flux_vals_overall_max_min_norm.describe()

,FLUX_0,FLUX_1,FLUX_2,FLUX_3,FLUX_4,FLUX_5,FLUX_6,FLUX_7,FLUX_8,FLUX_9,...,FLUX_399,FLUX_400,FLUX_401,FLUX_402,FLUX_403,FLUX_404,FLUX_405,FLUX_406,FLUX_407,FLUX_408
count,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,...,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000
mean,0.178467,0.185734,0.194813,0.205557,0.214658,0.217618,0.215909,0.212080,0.208242,0.207315,...,0.102523,0.101934,0.100784,0.099173,0.097715,0.097028,0.097556,0.097904,0.097382,0.096735
std,0.174389,0.180930,0.188604,0.197895,0.204586,0.205683,0.202849,0.197732,0.193069,0.190626,...,0.051373,0.050802,0.050028,0.048908,0.047920,0.047194,0.047534,0.047691,0.047396,0.046977
min,0.029173,0.029201,0.029198,0.029211,0.029246,0.029250,0.029241,0.029245,0.029152,0.029179,...,0.028964,0.028881,0.028929,0.028965,0.028965,0.028985,0.028951,0.028955,0.028987,0.028977
25%,0.052465,0.053217,0.055227,0.057057,0.059377,0.060911,0.061314,0.061376,0.062500,0.063118,...,0.067815,0.067329,0.066597,0.066449,0.065920,0.065707,0.066071,0.066030,0.065567,0.065673
50%,0.097994,0.102542,0.108175,0.114987,0.121348,0.124501,0.125024,0.122751,0.120682,0.121122,...,0.087089,0.087179,0.085604,0.084268,0.083252,0.083004,0.083350,0.083446,0.083020,0.082651
75%,0.257691,0.270761,0.287451,0.306511,0.322298,0.330919,0.325858,0.318308,0.309040,0.307973,...,0.142502,0.141869,0.139943,0.136941,0.134304,0.133633,0.134369,0.134772,0.133424,0.132411
max,0.818774,0.842258,0.855260,0.930815,0.931326,0.942256,0.938525,0.904625,0.864826,0.871486,...,0.259241,0.259088,0.252823,0.250607,0.245699,0.245349,0.243476,0.244557,0.241700,0.239583

## PCA

In [64]:
#NORMALIZE DATA FOR PCA
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
flux_vals_rescaled = scaler.fit_transform(flux_vals_normalized)
pd.DataFrame(flux_vals_rescaled).describe()

,0,1,2,3,4,5,6,7,8,9,...,399,400,401,402,403,404,405,406,407,408
count,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,...,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000
mean,0.432281,0.427560,0.458707,0.446436,0.469100,0.475415,0.477350,0.489061,0.513994,0.503179,...,0.286407,0.292530,0.286436,0.281255,0.280007,0.277604,0.274932,0.276106,0.271943,0.266666
std,0.206759,0.211628,0.214700,0.207363,0.214049,0.210514,0.204564,0.204709,0.205043,0.197375,...,0.112991,0.114165,0.112815,0.111905,0.112216,0.113381,0.110338,0.110888,0.109919,0.108065
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.284053,0.272340,0.298475,0.292616,0.311348,0.319691,0.327997,0.346940,0.380274,0.374853,...,0.239859,0.244490,0.239058,0.232768,0.231405,0.227377,0.225960,0.227408,0.221505,0.217805
50%,0.393619,0.396146,0.426971,0.419994,0.450801,0.465673,0.466809,0.477504,0.501899,0.492137,...,0.277668,0.284411,0.277474,0.273174,0.269632,0.265111,0.264768,0.265548,0.263212,0.256426
75%,0.566207,0.566779,0.607104,0.593365,0.625563,0.636142,0.626478,0.634948,0.651930,0.641550,...,0.334323,0.338453,0.332593,0.327736,0.323010,0.324323,0.319712,0.320932,0.317602,0.310450
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [79]:
#PCA
from sklearn.decomposition import PCA

pca = PCA(n_components = 0.97)
pca.fit(flux_vals_rescaled)
reduced_flux_vals = pca.transform(flux_vals_rescaled)
reduced_flux_vals = pd.DataFrame(reduced_flux_vals)

reduced_flux_vals.describe()

                  0             1             2             3             4
count  7.800000e+02  7.800000e+02  7.800000e+02  7.800000e+02  7.800000e+02
mean  -4.336133e-15  4.372571e-15  1.011157e-15 -1.919832e-15  1.766109e-15
std    2.269456e+00  1.878271e+00  5.326649e-01  3.514513e-01  2.671945e-01
min   -8.268057e+00 -5.312699e+00 -3.259426e+00 -1.122640e+00 -1.773632e+00
25%   -6.774719e-01 -1.482905e+00 -2.985041e-01 -2.033821e-01 -1.242573e-01
50%    1.454501e-01  1.636675e-01  8.793326e-02  2.213903e-02 -1.170611e-02
75%    1.124588e+00  1.539787e+00  3.937842e-01  2.191830e-01  1.149908e-01
max    8.257796e+00  3.523871e+00  1.104816e+00  1.573983e+00  1.154203e+00

## Random Forest

In [73]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [74]:
new_spt = singles["SPT"].str[0]
singles["SPT"] = new_spt

In [78]:
singles_drop = singles["SPT"]
singles_w_flux_vals = pd.concat([singles_drop, reduced_flux_vals], axis = 1)
singles_w_flux_vals.head()

  SPT         0         1         2         3         4
0   M -0.649538  2.882549 -0.572044  0.087704  0.101310
1   M -1.583240  2.720094 -0.666696 -0.426392 -0.163629
2   M -0.969981  2.704220 -0.934611  0.042386  0.122568
3   M -0.674746  3.523871 -0.814948  0.096004  0.147264
4   M -0.966344  2.875710 -0.937673 -0.061018  0.151090

In [81]:
X = singles_w_flux_vals.drop("SPT", axis = 1)
y = singles_w_flux_vals["SPT"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train, y_train)
preds = rf_classifier.predict(X_test)
preds[:5]

array(['L', 'L', 'L', 'L', 'L'], dtype=object)

In [82]:
ACC = np.mean(preds == y_test)

print(f"RF ACCURACY: {ACC}")

RF ACCURACY: 0.9829059829059829

## Hyperparameter Tuning (Grid Search)

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
y_train.value_counts()

SPT
L    378
M    233
T    123
Name: count, dtype: int64

In [21]:
rf_parameters = {'n_estimators': [50, 100, 200, 500],
                 'min_samples_split': [2, 5, 10],
                 'min_samples_leaf': [1, 2, 5, 10],
                 'max_depth' : [5, 7, 9, 10]}

CV_rfc = GridSearchCV(estimator = rf_classifier, param_grid = rf_parameters, scoring = 'accuracy', cv = 5)
CV_rfc.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [5, 7, 9, 10],
                         'min_samples_leaf': [1, 2, 5, 10],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 200, 500]},
             scoring='accuracy')

In [22]:
CV_rfc.best_params_

{'max_depth': 10,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 100}

In [25]:
rf_classifier = RandomForestClassifier(max_depth = 10, min_samples_leaf = 1, min_samples_split = 2, n_estimators = 100)
rf_classifier.fit(X_train, y_train)
preds = rf_classifier.predict(X_test)
preds[:5]

array(['L', 'T', 'L', 'T', 'M'], dtype=object)

In [26]:
ACC = np.mean(preds == y_test)

print(f"RF ACCURACY: {ACC}")

RF ACCURACY: 0.9682539682539683

In [27]:
preds = CV_rfc.predict(X_test)
preds[:5]

array(['L', 'T', 'L', 'T', 'M'], dtype=object)

In [28]:
ACC = np.mean(preds == y_test)

print(f"RF ACCURACY: {ACC}") #uses last hyperparam configuration it trained on

RF ACCURACY: 0.9650793650793651